use_frameworks!

target 'XTAdMobHelper_Example' do
  pod 'XTAdMobHelper', :path => '../'

  target 'XTAdMobHelper_Tests' do
    inherit! :search_paths

#   pod 'FBSnapshotTestCase'
	pod 'Google-Mobile-Ads-SDK'
  end
end
